const RATING_MIN_VALUE = 1;
const RATING_MAX_VALUE = 10;
const FILM_CREATE_MIN_YEAR = 1900;
const FILM_CREATE_MAX_YEAR = 2020;
const FILM_MIN_DURATION = 1200;
const FILM_MAX_DURATION = 14400;
const COMMENTS_MIN_COUNT = 1;
const COMMENTS_MAX_COUNT = 5;
const MAX_DESCRIPTION_LENGTH = 140;

const EMOJIS = [`smile`, `angry`, `puke`, `sleeping`];

export {RATING_MIN_VALUE, RATING_MAX_VALUE, FILM_CREATE_MIN_YEAR, FILM_CREATE_MAX_YEAR, FILM_MIN_DURATION, FILM_MAX_DURATION, COMMENTS_MIN_COUNT, COMMENTS_MAX_COUNT, MAX_DESCRIPTION_LENGTH, EMOJIS};
